external_data_config:
  external_data_csv: "https://raw.githubusercontent.com/abhi6174/ExoSeek/3d2c305aa9b9ca3536a0d10ed5e373167ae99182/dataset/kepler_exoplanet_detection.csv"

raw_data_config: 
  dir: data/raw
  train_file: kepler_raw.csv

processed_data_config:
  dir: data/processed
  train_file: train.csv
  test_file: test.csv
  target_col: koi_disposition

model_config:
  dir: backend/models
  model_name: exoplanet_model.pkl
  feature_list_name: model_features.json
  random_state: 42
  n_estimators: 200
  test_size: 0.2
  n_features_to_select: 10